version: '3'

services:
  ganache:
    image: sudeep162002/scm-ganache:latest
    ports:
      - "8545:8545"
    networks:
      - ganache-network
    container_name: my-ganache-container

  frontend1: # First instance of frontend
    image: sudeep162002/scm-frontend:latest
    networks:
      - ganache-network
    container_name: scmf1
    depends_on:
      - ganache

  frontend2: # Second instance of frontend
    image: sudeep162002/scm-frontend:latest
    networks:
      - ganache-network
    container_name: scmf2
    depends_on:
      - ganache

  nginx:
    image: nginx:latest
    ports:
      - "3000:80" # Expose Nginx on port 3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom Nginx configuration
    depends_on:
      - frontend1
      - frontend2
    networks:
      - ganache-network

networks:
  ganache-network:
    name: ganache-network
