# Use an official Node.js 16 Alpine Linux runtime as a base image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install --production

# Copy the rest of the application files to the working directory
COPY . .

# Expose the port on which your React app runs
EXPOSE 3000

# Command to run your React app
CMD ["npm", "start"]
